
name = "edge-tunnel"
compatibility_date = "2025-07-28"
main = "_worker.js"
type = "javascript"

account_id = "dc93ecb692666bf59c527cf28dc5dfbf"
workers_dev = true

compatibility_flags = ["nodejs_compat"]  # 可选，如使用 Node 语法

[build]
upload.format = "modules" 
